#### Sankalp Dayal (17BCE0693)

# Classification
### Using library function

In [21]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics 

In [22]:
from sklearn.datasets import load_iris
iris = load_iris()

In [23]:
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.25, random_state=1)

In [24]:
obj = DecisionTreeClassifier()

# Train Decision Tree Classifer
obj = obj.fit(X_train,y_train)

#Predict the response for test dataset
predictions = obj.predict(X_test)

In [25]:
predictions

array([0, 1, 1, 0, 2, 1, 2, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       2, 0, 2, 1, 0, 0, 1, 2, 1, 2, 1, 2, 2, 0, 1, 0])

In [39]:
print("Accuracy : {:.5f}".format(metrics.accuracy_score(y_test, predictions)))

Accuracy : 0.97368


In [27]:
from sklearn.metrics import confusion_matrix
conf_mat = confusion_matrix(y_test,predictions)
print("Confusion matrix : \n", conf_mat)

Confusion matrix : 
 [[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]


In [28]:
from sklearn.metrics import classification_report
report = classification_report(y_test, predictions)
print("Classification Report : \n\n",report)

Classification Report : 

               precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      0.94      0.97        16
           2       0.90      1.00      0.95         9

    accuracy                           0.97        38
   macro avg       0.97      0.98      0.97        38
weighted avg       0.98      0.97      0.97        38



In [29]:
from sklearn.metrics import accuracy_score
acc = accuracy_score(y_test,predictions)
print("Accuracy : {:.5f}".format(acc))

Accuracy : 0.97368


### Without using library function

In [30]:
import numpy as np
from sklearn.metrics import classification_report, accuracy_score
from sklearn.model_selection import train_test_split
class Node:
    def _init_(self, predicted_class):
        self.predicted_class = predicted_class
        self.feature_index = 0
        self.threshold = 0
        self.left = None
        self.right = None


class NDecisionTreeClassifier:
    def _init_(self, max_depth=None):
        self.max_depth = max_depth

    def fit(self, X, y):
        self.n_classes_ = len(set(y))
        self.n_features_ = X.shape[1]
        self.tree_ = self._grow_tree(X, y)

    def predict(self, X):
        return [self._predict(inputs) for inputs in X]

    def _best_split(self, X, y):
        m = y.size
        if m <= 1:
            return None, None
        num_parent = [np.sum(y == c) for c in range(self.n_classes_)]
        best_gini = 1.0 - sum((n / m) ** 2 for n in num_parent)
        best_idx, best_thr = None, None
        for idx in range(self.n_features_):
            thresholds, classes = zip(*sorted(zip(X[:, idx], y)))
            num_left = [0] * self.n_classes_
            num_right = num_parent.copy()
            for i in range(1, m):
                c = classes[i - 1]
                num_left[c] += 1
                num_right[c] -= 1
                gini_left = 1.0 - sum(
                    (num_left[x] / i) ** 2 for x in range(self.n_classes_)
                )
                gini_right = 1.0 - sum(
                    (num_right[x] / (m - i)) ** 2 for x in range(self.n_classes_)
                )
                gini = (i * gini_left + (m - i) * gini_right) / m
                if thresholds[i] == thresholds[i - 1]:
                    continue
                if gini < best_gini:
                    best_gini = gini
                    best_idx = idx
                    best_thr = (thresholds[i] + thresholds[i - 1]) / 2
        return best_idx, best_thr

    def _grow_tree(self, X, y, depth=0):
        num_samples_per_class = [np.sum(y == i) for i in range(self.n_classes_)]
        predicted_class = np.argmax(num_samples_per_class)
        node = Node()
        node._init_(predicted_class=predicted_class)
        if depth < self.max_depth:
            idx, thr = self._best_split(X, y)
            if idx is not None:
                indices_left = X[:, idx] < thr
                X_left, y_left = X[indices_left], y[indices_left]
                X_right, y_right = X[~indices_left], y[~indices_left]
                node.feature_index = idx
                node.threshold = thr
                node.left = self._grow_tree(X_left, y_left, depth + 1)
                node.right = self._grow_tree(X_right, y_right, depth + 1)
        return node

    def _predict(self, inputs):
        node = self.tree_
        while node.left:
            if inputs[node.feature_index] < node.threshold:
                node = node.left
            else:
                node = node.right
        return node.predicted_class

In [31]:
import sys
from sklearn.datasets import load_iris
iris = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.25, random_state=1)
clf = NDecisionTreeClassifier()
clf._init_(5)
clf.fit(X_train, y_train)
    #print(clf.predict())
    #y_pred = clf.predict(X_test)

    #print(y_pred)
    #print(y_test)
y_pred=clf.predict(X_test)
print(classification_report(y_test, y_pred, target_names=iris.target_names))
print('\nAccuracy: {0:.4f}'.format(accuracy_score(y_test, y_pred)))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        13
  versicolor       1.00      0.94      0.97        16
   virginica       0.90      1.00      0.95         9

    accuracy                           0.97        38
   macro avg       0.97      0.98      0.97        38
weighted avg       0.98      0.97      0.97        38


Accuracy: 0.9737


### Comparison of (i) and (ii)

In the above models we can see that the accuracy of both of them is 97%. So both the models are getting high accuracy. For the precision and recall, they are very close to each other. This is also valid for the f1-score and the support of the 2 models. Hence we can conclude that our model is very accurate and is getting almost same amount of accuracy as with the in built funtions.

# Regression
### Using library function

In [32]:
from sklearn.tree import DecisionTreeRegressor

regressor = DecisionTreeRegressor(random_state = 0)
regressor.fit(X_train,y_train)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=0, splitter='best')

In [33]:
Y_Pred = regressor.predict(X_test)
print("Accuracy is",metrics.accuracy_score(y_test, Y_Pred))

Accuracy is 0.9736842105263158


In [34]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result = confusion_matrix(y_test, Y_Pred)
print("Confusion Matrix:")
print(result)

Confusion Matrix:
[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]


In [35]:
result1 = classification_report(y_test, Y_Pred)
print("Classification Report:\n",)
print (result1)

Classification Report:

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      0.94      0.97        16
           2       0.90      1.00      0.95         9

    accuracy                           0.97        38
   macro avg       0.97      0.98      0.97        38
weighted avg       0.98      0.97      0.97        38



In [36]:
result2 = accuracy_score(y_test,Y_Pred)
print("Accuracy:",result2)

Accuracy: 0.9736842105263158
